- name: A playbook to deploy a docker image to kubernetes
  hosts: localhost
  user: ubuntu
  become: yes

  tasks:
  - name: 1. Update APT Package Manager
    apt:
      update_cache: yes

  - name: 2. Deploy to Kubernetes
    become: no
    shell:
      cmd: kubectl create deployment coursework2 --image=paulta91/coursework2:latest

  - name: 3. View deployment
    become: no
    shell:
      cmd: kubectl get deployments
